<?php
/**
 * Application Pack DOCX Generator
 *
 * Generates consulting-grade Word documents for Application Pack using PHPWord.
 *
 * @package SFFC_Careers
 * @since 1.0.0
 */

if (!defined('ABSPATH')) {
    exit;
}

require_once dirname(__FILE__) . '/class-application-pack-design-system.php';

class SFFC_Application_Pack_DOCX_Generator {

    /**
     * PHPWord instance
     */
    private $phpWord;

    /**
     * Current section
     */
    private $section;

    /**
     * Design system reference
     */
    private $design;

    /**
     * Constructor
     */
    public function __construct() {
        $this->design = new SFFC_Application_Pack_Design_System();
        $this->load_phpword();
    }

    /**
     * Load PHPWord library
     */
    private function load_phpword() {
        $autoload_path = SFFC_PLUGIN_DIR . 'vendor/autoload.php';

        if (!file_exists($autoload_path)) {
            throw new Exception('PHPWord library not found. Please install via Composer.');
        }

        require_once $autoload_path;
    }

    /**
     * Initialize document
     */
    private function init_document($title = 'Application Pack Document') {
        $this->phpWord = new \PhpOffice\PhpWord\PhpWord();

        // Document properties
        $properties = $this->phpWord->getDocInfo();
        $properties->setCreator('MENA Careers Finance');
        $properties->setCompany('MENA Careers Finance');
        $properties->setTitle($title);
        $properties->setDescription('Generated by MENA Careers Finance Application Pack');

        // Add custom styles
        $this->add_styles();

        // Create section with margins (in twips: 1 inch = 1440 twips)
        $this->section = $this->phpWord->addSection(array(
            'marginTop' => 720,    // 0.5 inch
            'marginBottom' => 720,
            'marginLeft' => 1080,  // 0.75 inch
            'marginRight' => 1080,
        ));
    }

    /**
     * Add custom styles
     */
    private function add_styles() {
        $colors = SFFC_Application_Pack_Design_System::COLORS;
        $typo = SFFC_Application_Pack_Design_System::TYPOGRAPHY;

        // Title style
        $this->phpWord->addTitleStyle(1, array(
            'name' => 'Arial',
            'size' => $typo['size_h1'],
            'bold' => true,
            'color' => ltrim($colors['primary'], '#'),
        ));

        // Heading 2 style
        $this->phpWord->addTitleStyle(2, array(
            'name' => 'Arial',
            'size' => $typo['size_h2'],
            'bold' => true,
            'color' => ltrim($colors['primary'], '#'),
            'allCaps' => true,
        ));

        // Paragraph styles
        $this->phpWord->addParagraphStyle('Normal', array(
            'spaceAfter' => 120,
            'lineHeight' => 1.15,
        ));

        $this->phpWord->addParagraphStyle('Executive', array(
            'spaceAfter' => 240,
            'lineHeight' => 1.3,
            'indentation' => array('left' => 240, 'right' => 240),
        ));

        $this->phpWord->addParagraphStyle('Bullet', array(
            'spaceAfter' => 60,
            'lineHeight' => 1.15,
        ));

        // Font styles
        $this->phpWord->addFontStyle('TitleFont', array(
            'name' => 'Arial',
            'size' => $typo['size_h1'],
            'bold' => true,
            'color' => ltrim($colors['primary'], '#'),
        ));

        $this->phpWord->addFontStyle('SubtitleFont', array(
            'name' => 'Arial',
            'size' => $typo['size_body'],
            'color' => ltrim($colors['text_medium'], '#'),
        ));

        $this->phpWord->addFontStyle('SectionHeader', array(
            'name' => 'Arial',
            'size' => $typo['size_h2'],
            'bold' => true,
            'color' => ltrim($colors['primary'], '#'),
            'allCaps' => true,
        ));

        $this->phpWord->addFontStyle('BodyBold', array(
            'name' => 'Arial',
            'size' => $typo['size_body'],
            'bold' => true,
            'color' => ltrim($colors['text_dark'], '#'),
        ));

        $this->phpWord->addFontStyle('BodyNormal', array(
            'name' => 'Arial',
            'size' => $typo['size_body'],
            'color' => ltrim($colors['text_dark'], '#'),
        ));

        $this->phpWord->addFontStyle('BodyItalic', array(
            'name' => 'Arial',
            'size' => $typo['size_body'],
            'italic' => true,
            'color' => ltrim($colors['text_medium'], '#'),
        ));

        $this->phpWord->addFontStyle('SmallText', array(
            'name' => 'Arial',
            'size' => $typo['size_small'],
            'color' => ltrim($colors['text_light'], '#'),
        ));
    }

    /**
     * Generate CV DOCX
     */
    public function generate_cv($cv_content, $job_data, $user_name) {
        $this->init_document($user_name . ' - CV - ' . $job_data['title']);

        $colors = SFFC_Application_Pack_Design_System::COLORS;

        // Header: Name
        $this->section->addText(
            $cv_content['header']['name'],
            'TitleFont',
            array('spaceAfter' => 60)
        );

        // Header: Subtitle
        $contact_parts = array();
        $contact_parts[] = $cv_content['header']['headline'];
        if (!empty($cv_content['header']['contact']['location'])) {
            $contact_parts[] = $cv_content['header']['contact']['location'];
        }
        if (!empty($cv_content['header']['contact']['email'])) {
            $contact_parts[] = $cv_content['header']['contact']['email'];
        }

        $this->section->addText(
            implode('  |  ', $contact_parts),
            'SubtitleFont',
            array('spaceAfter' => 360)
        );

        // Executive Summary
        $this->add_section_header('Executive Profile');
        $this->add_executive_box($cv_content['executive_summary']);

        // Two Column: Qualifications and Metrics
        $this->add_two_column_section(
            'Key Qualifications',
            $cv_content['key_qualifications'],
            'Core Metrics',
            $cv_content['metrics']
        );

        // Experience
        $this->add_section_header('Professional Experience');
        $this->add_experience($cv_content['experience']);

        // Skills
        $this->add_section_header('Skills & Expertise');
        $this->add_skills($cv_content['skills']);

        // Education
        if (!empty($cv_content['education'])) {
            $this->add_section_header('Education');
            $this->add_education($cv_content['education']);
        }

        // Footer
        $this->add_footer($job_data);

        // Generate and return
        $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($this->phpWord, 'Word2007');

        ob_start();
        $objWriter->save('php://output');
        return ob_get_clean();
    }

    /**
     * Add section header with gold underline
     */
    private function add_section_header($text) {
        $colors = SFFC_Application_Pack_Design_System::COLORS;

        $this->section->addText(
            strtoupper($text),
            'SectionHeader',
            array('spaceAfter' => 60, 'spaceBefore' => 240)
        );

        // Add a thin gold line (using a table with colored border)
        $table = $this->section->addTable(array(
            'borderBottomSize' => 12,
            'borderBottomColor' => ltrim($colors['secondary'], '#'),
            'cellMargin' => 0,
        ));
        $table->addRow();
        $table->addCell(4000)->addText('', array('size' => 1));

        $this->section->addTextBreak(1);
    }

    /**
     * Add executive summary box
     */
    private function add_executive_box($text) {
        $colors = SFFC_Application_Pack_Design_System::COLORS;

        // Create a table for the box effect
        $table = $this->section->addTable(array(
            'borderLeftSize' => 24,
            'borderLeftColor' => ltrim($colors['secondary'], '#'),
            'cellMargin' => 160,
        ));

        $table->addRow();
        $cell = $table->addCell(9000, array(
            'bgColor' => ltrim($colors['background_alt'], '#'),
        ));

        $cell->addText($text, 'BodyNormal', 'Executive');

        $this->section->addTextBreak(1);
    }

    /**
     * Add two column section
     */
    private function add_two_column_section($left_title, $left_items, $right_title, $right_items) {
        $table = $this->section->addTable();
        $table->addRow();

        // Left column
        $leftCell = $table->addCell(4500);
        $leftCell->addText($left_title, 'BodyBold', array('spaceAfter' => 120));

        foreach ($left_items as $item) {
            $leftCell->addListItem($item, 0, 'BodyNormal', null, 'Bullet');
        }

        // Right column
        $rightCell = $table->addCell(4500);
        $rightCell->addText($right_title, 'BodyBold', array('spaceAfter' => 120));

        foreach ($right_items as $metric) {
            if (is_array($metric)) {
                $textRun = $rightCell->addTextRun('Bullet');
                $textRun->addText($metric['value'] . '  ', array(
                    'bold' => true,
                    'size' => 12,
                    'color' => ltrim(SFFC_Application_Pack_Design_System::COLORS['primary'], '#'),
                ));
                $textRun->addText(strtoupper($metric['label']), 'SmallText');
            } else {
                $rightCell->addListItem($metric, 0, 'BodyNormal', null, 'Bullet');
            }
        }

        $this->section->addTextBreak(1);
    }

    /**
     * Add experience section
     */
    private function add_experience($experience) {
        foreach ($experience as $exp) {
            // Company and date row
            $table = $this->section->addTable();
            $table->addRow();
            $table->addCell(6000)->addText($exp['company'] ?? '', 'BodyBold');
            $table->addCell(3000)->addText(
                ($exp['start_date'] ?? '') . ' - ' . ($exp['end_date'] ?? 'Present'),
                'SmallText',
                array('alignment' => \PhpOffice\PhpWord\SimpleType\Jc::END)
            );

            // Job title
            $this->section->addText($exp['title'] ?? '', 'BodyItalic', array('spaceAfter' => 60));

            // Bullets
            if (!empty($exp['achievements'])) {
                foreach ($exp['achievements'] as $bullet) {
                    $bullet = strlen($bullet) > 180 ? substr($bullet, 0, 177) . '...' : $bullet;
                    $this->section->addListItem($bullet, 0, 'BodyNormal', null, 'Bullet');
                }
            }

            $this->section->addTextBreak(1);
        }
    }

    /**
     * Add skills section
     */
    private function add_skills($skills) {
        $colors = SFFC_Application_Pack_Design_System::COLORS;

        $all_skills = array_merge(
            $skills['matched'] ?? array(),
            $skills['additional'] ?? array()
        );

        if (empty($all_skills)) {
            return;
        }

        // Create skill tags as inline text
        $textRun = $this->section->addTextRun(array('spaceAfter' => 240));

        $matched_count = count($skills['matched'] ?? array());

        foreach ($all_skills as $index => $skill) {
            $is_matched = $index < $matched_count;

            // Add skill with background simulation using brackets
            if ($is_matched) {
                $textRun->addText('[' . $skill . ']  ', array(
                    'size' => 9,
                    'color' => ltrim($colors['primary'], '#'),
                    'bgColor' => 'E8F4F8',
                ));
            } else {
                $textRun->addText('[' . $skill . ']  ', array(
                    'size' => 9,
                    'color' => ltrim($colors['text_dark'], '#'),
                ));
            }
        }
    }

    /**
     * Add education section
     */
    private function add_education($education) {
        foreach ($education as $edu) {
            $table = $this->section->addTable();
            $table->addRow();
            $table->addCell(6000)->addText($edu['institution'] ?? '', 'BodyBold');
            $table->addCell(3000)->addText(
                $edu['year'] ?? '',
                'SmallText',
                array('alignment' => \PhpOffice\PhpWord\SimpleType\Jc::END)
            );

            $this->section->addText($edu['degree'] ?? '', 'BodyItalic', array('spaceAfter' => 120));
        }
    }

    /**
     * Add footer
     */
    private function add_footer($job_data) {
        $colors = SFFC_Application_Pack_Design_System::COLORS;

        $this->section->addTextBreak(2);

        // Divider line
        $table = $this->section->addTable(array(
            'borderTopSize' => 6,
            'borderTopColor' => ltrim($colors['border'], '#'),
        ));
        $table->addRow();
        $table->addCell(9000)->addText('', array('size' => 1));

        // Footer text
        $this->section->addText(
            'Tailored for ' . $job_data['title'] . ' at ' . $job_data['company'],
            'SmallText',
            array('alignment' => \PhpOffice\PhpWord\SimpleType\Jc::CENTER, 'spaceBefore' => 120)
        );
    }

    /**
     * Save DOCX to file
     */
    public function save_to_file($content, $filename) {
        $upload_dir = wp_upload_dir();
        $pack_dir = $upload_dir['basedir'] . '/sffc-application-packs';

        if (!file_exists($pack_dir)) {
            wp_mkdir_p($pack_dir);
            file_put_contents($pack_dir . '/.htaccess', 'deny from all');
        }

        $file_path = $pack_dir . '/' . $filename;
        file_put_contents($file_path, $content);

        return array(
            'path' => $file_path,
            'url' => $upload_dir['baseurl'] . '/sffc-application-packs/' . $filename,
        );
    }

    /**
     * Generate cover letter DOCX
     */
    public function generate_cover_letter($content, $job_data, $user_name) {
        $this->init_document($user_name . ' - Cover Letter - ' . $job_data['company']);

        // Date (right aligned)
        $this->section->addText(
            date('F j, Y'),
            'BodyNormal',
            array('alignment' => \PhpOffice\PhpWord\SimpleType\Jc::END, 'spaceAfter' => 360)
        );

        // Recipient
        if (!empty($content['recipient'])) {
            $this->section->addText($content['recipient'], 'BodyNormal');
        }
        $this->section->addText($job_data['company'], 'BodyNormal', array('spaceAfter' => 360));

        // Subject line
        $this->section->addText(
            'RE: ' . $job_data['title'] . ' Application',
            'BodyBold',
            array('spaceAfter' => 240)
        );

        // Body paragraphs
        foreach ($content['paragraphs'] as $paragraph) {
            $this->section->addText($paragraph, 'BodyNormal', array('spaceAfter' => 240));
        }

        // Closing
        $this->section->addText('Regards,', 'BodyNormal', array('spaceBefore' => 360, 'spaceAfter' => 480));
        $this->section->addText($content['sender_name'], 'BodyBold');

        // Contact
        $contact = array();
        if (!empty($content['phone'])) $contact[] = $content['phone'];
        if (!empty($content['email'])) $contact[] = $content['email'];
        if (!empty($content['linkedin'])) $contact[] = $content['linkedin'];

        $this->section->addText(implode('  |  ', $contact), 'SmallText');

        // Generate
        $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($this->phpWord, 'Word2007');
        ob_start();
        $objWriter->save('php://output');
        return ob_get_clean();
    }
}
