<?php
/**
 * Deal Excel Generator
 * Generates professional Excel financial models for deal articles
 *
 * @package SFFC
 * @since 1.0.0
 */

if (!defined('ABSPATH')) {
    exit;
}

// Include vendor autoloader
require_once dirname(__FILE__) . '/vendor-autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;

if (!class_exists('SFFC_Deal_Excel_Generator')) {

class SFFC_Deal_Excel_Generator {

    /**
     * Export directory path
     */
    private $export_dir;

    /**
     * Generated files directory
     */
    private $generated_dir;

    /**
     * Brand colors
     */
    private $colors = array(
        'navy'       => '132D51',
        'green'      => '2D6A4F',
        'light_blue' => 'E8F4FD',
        'light_green'=> 'E8F5E9',
        'gray'       => 'F5F5F5',
        'border'     => 'D1D5DB',
        'text'       => '374151',
        'muted'      => '6B7280',
        'positive'   => '059669',
        'negative'   => 'DC2626',
        'warning'    => 'D97706',
    );

    /**
     * Constructor
     */
    public function __construct() {
        $this->export_dir = plugin_dir_path(dirname(__FILE__)) . 'exports/';
        $this->generated_dir = $this->export_dir . 'generated/';

        $this->ensure_directories();
    }

    /**
     * Ensure export directories exist
     */
    private function ensure_directories() {
        $dirs = array($this->export_dir, $this->generated_dir);

        foreach ($dirs as $dir) {
            if (!file_exists($dir)) {
                wp_mkdir_p($dir);
            }
        }
    }

    /**
     * Generate Excel model for a deal article
     *
     * @param int $post_id Post ID of the deal article
     * @return array Result with success status and download URL
     */
    public function generate($post_id) {
        try {
            // Check if libraries are loaded
            if (!defined('SFFC_LIBRARIES_LOADED') || !SFFC_LIBRARIES_LOADED) {
                throw new Exception('Export libraries not installed.');
            }

            // Check if PhpSpreadsheet is available
            if (!class_exists('PhpOffice\PhpSpreadsheet\Spreadsheet')) {
                throw new Exception('PhpSpreadsheet library not found.');
            }

            // Get post data
            $post = get_post($post_id);
            if (!$post) {
                throw new Exception('Article not found.');
            }

            // Get deal financials meta
            $deal_financials = get_post_meta($post_id, '_sffc_deal_financials', true);
            if (empty($deal_financials)) {
                throw new Exception('No deal financials available for this article.');
            }

            // Create spreadsheet
            $spreadsheet = new Spreadsheet();

            // Set document properties
            $spreadsheet->getProperties()
                ->setCreator('MENA Careers')
                ->setLastModifiedBy('MENA Careers')
                ->setTitle('Deal Analysis - ' . $post->post_title)
                ->setSubject('Financial Model')
                ->setDescription('Investment analysis model generated by MENA Careers')
                ->setKeywords('deal analysis financial model PE')
                ->setCategory('Financial Analysis');

            // Build sheets
            $this->build_summary_sheet($spreadsheet, $post, $deal_financials);
            $this->build_transaction_sheet($spreadsheet, $post, $deal_financials);
            $this->build_financials_sheet($spreadsheet, $post, $deal_financials);
            $this->build_comparables_sheet($spreadsheet, $post, $deal_financials);
            $this->build_scenario_sheet($spreadsheet, $post, $deal_financials);
            $this->build_sensitivity_sheet($spreadsheet, $post, $deal_financials);
            $this->build_risks_sheet($spreadsheet, $post, $deal_financials);
            $this->build_sources_sheet($spreadsheet, $post, $deal_financials);

            // Set active sheet to Summary
            $spreadsheet->setActiveSheetIndex(0);

            // Generate filename
            $filename = $this->generate_filename($post);
            $filepath = $this->generated_dir . $filename;

            // Save file
            $writer = new Xlsx($spreadsheet);
            $writer->save($filepath);

            // Generate download URL
            $download_url = $this->create_download_url($filename, $post_id);

            // Track download
            $this->track_download($post_id);

            return array(
                'success' => true,
                'filename' => $filename,
                'filepath' => $filepath,
                'download_url' => $download_url,
                'format' => 'xlsx'
            );

        } catch (Exception $e) {
            error_log('Deal Excel Generator Error: ' . $e->getMessage());
            return array(
                'success' => false,
                'message' => $e->getMessage()
            );
        }
    }

    /**
     * Build Executive Summary sheet
     */
    private function build_summary_sheet($spreadsheet, $post, $deal_financials) {
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Executive Summary');

        // Set column widths
        $sheet->getColumnDimension('A')->setWidth(25);
        $sheet->getColumnDimension('B')->setWidth(20);
        $sheet->getColumnDimension('C')->setWidth(20);
        $sheet->getColumnDimension('D')->setWidth(15);
        $sheet->getColumnDimension('E')->setWidth(15);

        // Header
        $sheet->setCellValue('A1', 'DEAL ANALYSIS');
        $sheet->mergeCells('A1:E1');
        $this->style_header($sheet, 'A1:E1');

        // Deal title
        $sheet->setCellValue('A3', $post->post_title);
        $sheet->mergeCells('A3:E3');
        $sheet->getStyle('A3')->getFont()->setBold(true)->setSize(14);

        // Date
        $sheet->setCellValue('A4', 'Analysis Date: ' . date('F j, Y'));
        $sheet->getStyle('A4')->getFont()->setColor(new Color($this->colors['muted']));

        // Key Metrics Section
        $sheet->setCellValue('A6', 'KEY METRICS');
        $this->style_section_header($sheet, 'A6');

        $row = 7;

        // Deal Value
        if (!empty($deal_financials['deal_value'])) {
            $sheet->setCellValue('A' . $row, 'Deal Value');
            $sheet->setCellValue('B' . $row, $deal_financials['deal_value']['formatted'] ?? $this->format_currency($deal_financials['deal_value']['amount'] ?? 0, $deal_financials['deal_value']['currency'] ?? 'USD'));
            $sheet->setCellValue('C' . $row, $this->get_source_label($deal_financials['deal_value']['source'] ?? 'unknown'));
            $row++;
        }

        // Net Proceeds
        if (!empty($deal_financials['net_proceeds']['amount'])) {
            $sheet->setCellValue('A' . $row, 'Net Proceeds');
            $sheet->setCellValue('B' . $row, $deal_financials['net_proceeds']['formatted'] ?? $this->format_currency($deal_financials['net_proceeds']['amount'], $deal_financials['net_proceeds']['currency'] ?? 'USD'));
            $sheet->setCellValue('C' . $row, $this->get_source_label($deal_financials['net_proceeds']['source'] ?? 'unknown'));
            $row++;
        }

        // Deal Type
        if (!empty($deal_financials['deal_type'])) {
            $sheet->setCellValue('A' . $row, 'Deal Type');
            $sheet->setCellValue('B' . $row, ucfirst($deal_financials['deal_type']));
            $row++;
        }

        // Sector
        if (!empty($deal_financials['sector'])) {
            $sheet->setCellValue('A' . $row, 'Sector');
            $sheet->setCellValue('B' . $row, $deal_financials['sector']);
            $row++;
        }

        // Region
        if (!empty($deal_financials['region'])) {
            $sheet->setCellValue('A' . $row, 'Region');
            $sheet->setCellValue('B' . $row, $deal_financials['region']);
            $row++;
        }

        $row++;

        // Multiples Section
        if (!empty($deal_financials['multiples'])) {
            $sheet->setCellValue('A' . $row, 'VALUATION MULTIPLES');
            $this->style_section_header($sheet, 'A' . $row);
            $row++;

            $multiples = $deal_financials['multiples'];

            if (!empty($multiples['ev_revenue']['value'])) {
                $sheet->setCellValue('A' . $row, 'EV / Revenue');
                $sheet->setCellValue('B' . $row, number_format($multiples['ev_revenue']['value'], 1) . 'x');
                $sheet->setCellValue('C' . $row, $this->get_source_label($multiples['ev_revenue']['source'] ?? 'unknown'));
                $row++;
            }

            if (!empty($multiples['ev_ebitda']['value'])) {
                $sheet->setCellValue('A' . $row, 'EV / EBITDA');
                $sheet->setCellValue('B' . $row, number_format($multiples['ev_ebitda']['value'], 1) . 'x');
                $sheet->setCellValue('C' . $row, $this->get_source_label($multiples['ev_ebitda']['source'] ?? 'unknown'));
                $row++;
            }

            if (!empty($multiples['ev_operating_profit']['value'])) {
                $sheet->setCellValue('A' . $row, 'EV / Operating Profit');
                $sheet->setCellValue('B' . $row, number_format($multiples['ev_operating_profit']['value'], 1) . 'x');
                $sheet->setCellValue('C' . $row, $this->get_source_label($multiples['ev_operating_profit']['source'] ?? 'unknown'));
                $row++;
            }

            if (!empty($multiples['ev_net_income']['value'])) {
                $sheet->setCellValue('A' . $row, 'EV / Net Income');
                $sheet->setCellValue('B' . $row, number_format($multiples['ev_net_income']['value'], 1) . 'x');
                $sheet->setCellValue('C' . $row, $this->get_source_label($multiples['ev_net_income']['source'] ?? 'unknown'));
                $row++;
            }
        }

        $row++;

        // Scenario Summary
        if (!empty($deal_financials['ai_enhanced']['scenarios'])) {
            $sheet->setCellValue('A' . $row, 'SCENARIO SUMMARY');
            $this->style_section_header($sheet, 'A' . $row);
            $row++;

            // Headers
            $sheet->setCellValue('A' . $row, 'Scenario');
            $sheet->setCellValue('B' . $row, 'IRR');
            $sheet->setCellValue('C' . $row, 'MOIC');
            $sheet->setCellValue('D' . $row, 'Exit Year');
            $this->style_table_header($sheet, 'A' . $row . ':D' . $row);
            $row++;

            $scenarios = $deal_financials['ai_enhanced']['scenarios'];

            foreach (array('base', 'upside', 'downside') as $type) {
                if (!empty($scenarios[$type])) {
                    $scenario = $scenarios[$type];
                    $sheet->setCellValue('A' . $row, ucfirst($type) . ' Case');
                    $sheet->setCellValue('B' . $row, ($scenario['irr'] ?? 0) . '%');
                    $sheet->setCellValue('C' . $row, ($scenario['moic'] ?? 0) . 'x');
                    $sheet->setCellValue('D' . $row, 'Year ' . ($scenario['exit_year'] ?? 5));

                    // Color code by scenario type
                    $color = $type === 'upside' ? $this->colors['positive'] : ($type === 'downside' ? $this->colors['negative'] : $this->colors['text']);
                    $sheet->getStyle('B' . $row)->getFont()->setColor(new Color($color));
                    $row++;
                }
            }
        }

        $row += 2;

        // Data Quality
        if (!empty($deal_financials['data_quality'])) {
            $sheet->setCellValue('A' . $row, 'DATA QUALITY ASSESSMENT');
            $this->style_section_header($sheet, 'A' . $row);
            $row++;

            $dq = $deal_financials['data_quality'];

            $sheet->setCellValue('A' . $row, 'Overall Score');
            $sheet->setCellValue('B' . $row, ($dq['overall_score'] ?? 0) . '%');
            $row++;

            $sheet->setCellValue('A' . $row, 'Disclosed Metrics');
            $sheet->setCellValue('B' . $row, $dq['disclosed_count'] ?? 0);
            $row++;

            $sheet->setCellValue('A' . $row, 'Calculated Metrics');
            $sheet->setCellValue('B' . $row, $dq['calculated_count'] ?? 0);
            $row++;

            $sheet->setCellValue('A' . $row, 'Estimated Metrics');
            $sheet->setCellValue('B' . $row, $dq['estimated_count'] ?? 0);
            $row++;
        }

        // Apply borders to data area
        $this->apply_borders($sheet, 'A6:D' . $row);
    }

    /**
     * Build Transaction Details sheet
     */
    private function build_transaction_sheet($spreadsheet, $post, $deal_financials) {
        $sheet = $spreadsheet->createSheet();
        $sheet->setTitle('Transaction Details');

        // Set column widths
        $sheet->getColumnDimension('A')->setWidth(25);
        $sheet->getColumnDimension('B')->setWidth(30);
        $sheet->getColumnDimension('C')->setWidth(15);

        // Header
        $sheet->setCellValue('A1', 'TRANSACTION DETAILS');
        $sheet->mergeCells('A1:C1');
        $this->style_header($sheet, 'A1:C1');

        $row = 3;

        // Deal Information
        $sheet->setCellValue('A' . $row, 'DEAL INFORMATION');
        $this->style_section_header($sheet, 'A' . $row);
        $row++;

        // Headers
        $sheet->setCellValue('A' . $row, 'Item');
        $sheet->setCellValue('B' . $row, 'Value');
        $sheet->setCellValue('C' . $row, 'Source');
        $this->style_table_header($sheet, 'A' . $row . ':C' . $row);
        $row++;

        // Deal Value
        $sheet->setCellValue('A' . $row, 'Enterprise Value');
        $sheet->setCellValue('B' . $row, $deal_financials['deal_value']['formatted'] ?? 'N/A');
        $sheet->setCellValue('C' . $row, $this->get_source_label($deal_financials['deal_value']['source'] ?? 'unknown'));
        $row++;

        // Net Proceeds
        if (!empty($deal_financials['net_proceeds']['amount'])) {
            $sheet->setCellValue('A' . $row, 'Net Proceeds');
            $sheet->setCellValue('B' . $row, $deal_financials['net_proceeds']['formatted'] ?? 'N/A');
            $sheet->setCellValue('C' . $row, $this->get_source_label($deal_financials['net_proceeds']['source'] ?? 'unknown'));
            $row++;
        }

        // Deal Type
        $sheet->setCellValue('A' . $row, 'Transaction Type');
        $sheet->setCellValue('B' . $row, ucfirst($deal_financials['deal_type'] ?? 'Unknown'));
        $row++;

        // Deal Stage
        if (!empty($deal_financials['deal_stage'])) {
            $sheet->setCellValue('A' . $row, 'Deal Stage');
            $sheet->setCellValue('B' . $row, ucfirst($deal_financials['deal_stage']));
            $row++;
        }

        $row++;

        // Buyer Information
        if (!empty($deal_financials['buyer'])) {
            $sheet->setCellValue('A' . $row, 'BUYER INFORMATION');
            $this->style_section_header($sheet, 'A' . $row);
            $row++;

            $buyer = $deal_financials['buyer'];

            $sheet->setCellValue('A' . $row, 'Buyer Name');
            $sheet->setCellValue('B' . $row, $buyer['name'] ?? 'N/A');
            $row++;

            if (!empty($buyer['type'])) {
                $sheet->setCellValue('A' . $row, 'Buyer Type');
                $sheet->setCellValue('B' . $row, ucfirst(str_replace('_', ' ', $buyer['type'])));
                $row++;
            }

            if (!empty($buyer['typical_hold_period'])) {
                $sheet->setCellValue('A' . $row, 'Typical Hold Period');
                $sheet->setCellValue('B' . $row, $buyer['typical_hold_period']);
                $row++;
            }
        }

        $row++;

        // Seller Information
        if (!empty($deal_financials['seller'])) {
            $sheet->setCellValue('A' . $row, 'SELLER INFORMATION');
            $this->style_section_header($sheet, 'A' . $row);
            $row++;

            $seller = $deal_financials['seller'];

            $sheet->setCellValue('A' . $row, 'Seller Name');
            $sheet->setCellValue('B' . $row, $seller['name'] ?? 'N/A');
            $row++;

            if (!empty($seller['ticker'])) {
                $sheet->setCellValue('A' . $row, 'Ticker');
                $sheet->setCellValue('B' . $row, $seller['ticker']);
                $row++;
            }

            if (!empty($seller['stock_impact'])) {
                $sheet->setCellValue('A' . $row, 'Stock Impact');
                $sheet->setCellValue('B' . $row, $seller['stock_impact']);
                $row++;
            }
        }

        // Apply borders
        $this->apply_borders($sheet, 'A3:C' . $row);
    }

    /**
     * Build Target Financials sheet
     */
    private function build_financials_sheet($spreadsheet, $post, $deal_financials) {
        $sheet = $spreadsheet->createSheet();
        $sheet->setTitle('Target Financials');

        // Set column widths
        $sheet->getColumnDimension('A')->setWidth(25);
        $sheet->getColumnDimension('B')->setWidth(20);
        $sheet->getColumnDimension('C')->setWidth(15);
        $sheet->getColumnDimension('D')->setWidth(30);

        // Header
        $sheet->setCellValue('A1', 'TARGET COMPANY FINANCIALS');
        $sheet->mergeCells('A1:D1');
        $this->style_header($sheet, 'A1:D1');

        $row = 3;

        // Financial Metrics
        $sheet->setCellValue('A' . $row, 'FINANCIAL METRICS');
        $this->style_section_header($sheet, 'A' . $row);
        $row++;

        // Headers
        $sheet->setCellValue('A' . $row, 'Metric');
        $sheet->setCellValue('B' . $row, 'Value');
        $sheet->setCellValue('C' . $row, 'Source');
        $sheet->setCellValue('D' . $row, 'Notes');
        $this->style_table_header($sheet, 'A' . $row . ':D' . $row);
        $row++;

        $financials = $deal_financials['target_financials'] ?? array();

        // Revenue
        if (!empty($financials['revenue']['amount'])) {
            $sheet->setCellValue('A' . $row, 'Revenue');
            $sheet->setCellValue('B' . $row, $this->format_currency($financials['revenue']['amount'], $financials['revenue']['currency'] ?? 'USD'));
            $sheet->setCellValue('C' . $row, $this->get_source_label($financials['revenue']['source'] ?? 'unknown'));
            $sheet->setCellValue('D' . $row, $financials['revenue']['notes'] ?? '');
            $row++;
        }

        // EBITDA
        if (!empty($financials['ebitda']['amount'])) {
            $sheet->setCellValue('A' . $row, 'EBITDA');
            $sheet->setCellValue('B' . $row, $this->format_currency($financials['ebitda']['amount'], $financials['ebitda']['currency'] ?? 'USD'));
            $sheet->setCellValue('C' . $row, $this->get_source_label($financials['ebitda']['source'] ?? 'unknown'));
            $sheet->setCellValue('D' . $row, $financials['ebitda']['notes'] ?? '');
            $row++;
        }

        // Operating Profit
        if (!empty($financials['operating_profit']['amount'])) {
            $sheet->setCellValue('A' . $row, 'Operating Profit');
            $sheet->setCellValue('B' . $row, $this->format_currency($financials['operating_profit']['amount'], $financials['operating_profit']['currency'] ?? 'USD'));
            $sheet->setCellValue('C' . $row, $this->get_source_label($financials['operating_profit']['source'] ?? 'unknown'));
            $sheet->setCellValue('D' . $row, $financials['operating_profit']['notes'] ?? '');
            $row++;
        }

        // Net Income
        if (!empty($financials['net_income']['amount'])) {
            $sheet->setCellValue('A' . $row, 'Net Income');
            $sheet->setCellValue('B' . $row, $this->format_currency($financials['net_income']['amount'], $financials['net_income']['currency'] ?? 'USD'));
            $sheet->setCellValue('C' . $row, $this->get_source_label($financials['net_income']['source'] ?? 'unknown'));
            $sheet->setCellValue('D' . $row, $financials['net_income']['notes'] ?? '');
            $row++;
        }

        $row++;

        // Margins
        $sheet->setCellValue('A' . $row, 'MARGIN ANALYSIS');
        $this->style_section_header($sheet, 'A' . $row);
        $row++;

        if (!empty($financials['ebitda_margin'])) {
            $sheet->setCellValue('A' . $row, 'EBITDA Margin');
            $sheet->setCellValue('B' . $row, number_format($financials['ebitda_margin'], 1) . '%');
            $sheet->setCellValue('C' . $row, $this->get_source_label($financials['ebitda_margin_source'] ?? 'calculated'));
            $row++;
        }

        if (!empty($financials['operating_margin'])) {
            $sheet->setCellValue('A' . $row, 'Operating Margin');
            $sheet->setCellValue('B' . $row, number_format($financials['operating_margin'], 1) . '%');
            $sheet->setCellValue('C' . $row, $this->get_source_label($financials['operating_margin_source'] ?? 'calculated'));
            $row++;
        }

        if (!empty($financials['net_margin'])) {
            $sheet->setCellValue('A' . $row, 'Net Margin');
            $sheet->setCellValue('B' . $row, number_format($financials['net_margin'], 1) . '%');
            $sheet->setCellValue('C' . $row, $this->get_source_label($financials['net_margin_source'] ?? 'calculated'));
            $row++;
        }

        $row++;

        // Growth Metrics
        if (!empty($financials['revenue_growth']) || !empty($financials['ebitda_growth'])) {
            $sheet->setCellValue('A' . $row, 'GROWTH METRICS');
            $this->style_section_header($sheet, 'A' . $row);
            $row++;

            if (!empty($financials['revenue_growth'])) {
                $sheet->setCellValue('A' . $row, 'Revenue Growth');
                $sheet->setCellValue('B' . $row, number_format($financials['revenue_growth'], 1) . '%');
                $sheet->setCellValue('C' . $row, $this->get_source_label($financials['revenue_growth_source'] ?? 'estimated'));
                $row++;
            }

            if (!empty($financials['ebitda_growth'])) {
                $sheet->setCellValue('A' . $row, 'EBITDA Growth');
                $sheet->setCellValue('B' . $row, number_format($financials['ebitda_growth'], 1) . '%');
                $sheet->setCellValue('C' . $row, $this->get_source_label($financials['ebitda_growth_source'] ?? 'estimated'));
                $row++;
            }
        }

        // Apply borders
        $this->apply_borders($sheet, 'A3:D' . $row);
    }

    /**
     * Build Comparable Transactions sheet
     */
    private function build_comparables_sheet($spreadsheet, $post, $deal_financials) {
        $sheet = $spreadsheet->createSheet();
        $sheet->setTitle('Comparable Analysis');

        // Set column widths
        $sheet->getColumnDimension('A')->setWidth(25);
        $sheet->getColumnDimension('B')->setWidth(20);
        $sheet->getColumnDimension('C')->setWidth(12);
        $sheet->getColumnDimension('D')->setWidth(12);
        $sheet->getColumnDimension('E')->setWidth(12);
        $sheet->getColumnDimension('F')->setWidth(12);

        // Header
        $sheet->setCellValue('A1', 'COMPARABLE TRANSACTIONS');
        $sheet->mergeCells('A1:F1');
        $this->style_header($sheet, 'A1:F1');

        $row = 3;

        // Current Deal Reference
        $sheet->setCellValue('A' . $row, 'CURRENT TRANSACTION');
        $this->style_section_header($sheet, 'A' . $row);
        $row++;

        $sheet->setCellValue('A' . $row, 'Target');
        $sheet->setCellValue('B' . $row, 'Buyer');
        $sheet->setCellValue('C' . $row, 'Date');
        $sheet->setCellValue('D' . $row, 'EV');
        $sheet->setCellValue('E' . $row, 'EV/EBITDA');
        $sheet->setCellValue('F' . $row, 'EV/Rev');
        $this->style_table_header($sheet, 'A' . $row . ':F' . $row);
        $row++;

        // Current deal
        $target_name = '';
        if (!empty($deal_financials['companies_involved'])) {
            $companies = $deal_financials['companies_involved'];
            $target_name = is_array($companies) ? ($companies[0] ?? 'Target') : $companies;
        }

        $buyer_name = $deal_financials['buyer']['name'] ?? $deal_financials['pe_firm'] ?? 'Buyer';

        $sheet->setCellValue('A' . $row, $target_name);
        $sheet->setCellValue('B' . $row, $buyer_name);
        $sheet->setCellValue('C' . $row, date('M Y'));
        $sheet->setCellValue('D' . $row, $deal_financials['deal_value']['formatted'] ?? 'N/A');
        $sheet->setCellValue('E' . $row, !empty($deal_financials['multiples']['ev_ebitda']['value']) ? number_format($deal_financials['multiples']['ev_ebitda']['value'], 1) . 'x' : 'N/A');
        $sheet->setCellValue('F' . $row, !empty($deal_financials['multiples']['ev_revenue']['value']) ? number_format($deal_financials['multiples']['ev_revenue']['value'], 1) . 'x' : 'N/A');
        $sheet->getStyle('A' . $row . ':F' . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FF' . $this->colors['light_blue']);
        $row++;

        $row++;

        // Comparable Transactions
        $comparables = $deal_financials['ai_enhanced']['comparables'] ?? $deal_financials['comparables'] ?? array();

        if (!empty($comparables)) {
            $sheet->setCellValue('A' . $row, 'COMPARABLE TRANSACTIONS');
            $this->style_section_header($sheet, 'A' . $row);
            $row++;

            $sheet->setCellValue('A' . $row, 'Target');
            $sheet->setCellValue('B' . $row, 'Buyer');
            $sheet->setCellValue('C' . $row, 'Date');
            $sheet->setCellValue('D' . $row, 'EV');
            $sheet->setCellValue('E' . $row, 'EV/EBITDA');
            $sheet->setCellValue('F' . $row, 'EV/Rev');
            $this->style_table_header($sheet, 'A' . $row . ':F' . $row);
            $row++;

            foreach ($comparables as $comp) {
                $sheet->setCellValue('A' . $row, $comp['target'] ?? 'N/A');
                $sheet->setCellValue('B' . $row, $comp['buyer'] ?? 'N/A');
                $sheet->setCellValue('C' . $row, $comp['date'] ?? 'N/A');
                $sheet->setCellValue('D' . $row, $comp['deal_value'] ?? 'N/A');
                $sheet->setCellValue('E' . $row, !empty($comp['ev_ebitda']) ? number_format($comp['ev_ebitda'], 1) . 'x' : 'N/A');
                $sheet->setCellValue('F' . $row, !empty($comp['ev_revenue']) ? number_format($comp['ev_revenue'], 1) . 'x' : 'N/A');
                $row++;
            }

            $row++;

            // Comparables Analysis Summary
            if (count($comparables) > 0) {
                $sheet->setCellValue('A' . $row, 'COMPARABLES SUMMARY');
                $this->style_section_header($sheet, 'A' . $row);
                $row++;

                // Calculate averages
                $ebitda_multiples = array_filter(array_column($comparables, 'ev_ebitda'));
                $revenue_multiples = array_filter(array_column($comparables, 'ev_revenue'));

                if (!empty($ebitda_multiples)) {
                    $avg_ebitda = array_sum($ebitda_multiples) / count($ebitda_multiples);
                    $sheet->setCellValue('A' . $row, 'Avg EV/EBITDA (Comps)');
                    $sheet->setCellValue('B' . $row, number_format($avg_ebitda, 1) . 'x');
                    $row++;

                    $current_ebitda = $deal_financials['multiples']['ev_ebitda']['value'] ?? null;
                    if ($current_ebitda) {
                        $premium = (($current_ebitda / $avg_ebitda) - 1) * 100;
                        $sheet->setCellValue('A' . $row, 'Premium / (Discount) to Avg');
                        $sheet->setCellValue('B' . $row, ($premium >= 0 ? '+' : '') . number_format($premium, 1) . '%');
                        $sheet->getStyle('B' . $row)->getFont()->setColor(new Color($premium >= 0 ? $this->colors['positive'] : $this->colors['negative']));
                        $row++;
                    }
                }
            }
        } else {
            $sheet->setCellValue('A' . $row, 'No comparable transactions available.');
            $sheet->getStyle('A' . $row)->getFont()->setItalic(true)->setColor(new Color($this->colors['muted']));
        }

        // Apply borders
        $this->apply_borders($sheet, 'A3:F' . $row);
    }

    /**
     * Build Scenario Analysis sheet
     */
    private function build_scenario_sheet($spreadsheet, $post, $deal_financials) {
        $sheet = $spreadsheet->createSheet();
        $sheet->setTitle('Scenario Analysis');

        // Set column widths
        $sheet->getColumnDimension('A')->setWidth(25);
        $sheet->getColumnDimension('B')->setWidth(18);
        $sheet->getColumnDimension('C')->setWidth(18);
        $sheet->getColumnDimension('D')->setWidth(18);

        // Header
        $sheet->setCellValue('A1', 'SCENARIO ANALYSIS');
        $sheet->mergeCells('A1:D1');
        $this->style_header($sheet, 'A1:D1');

        $row = 3;

        $scenarios = $deal_financials['ai_enhanced']['scenarios'] ?? $deal_financials['scenarios'] ?? array();

        if (empty($scenarios)) {
            $sheet->setCellValue('A' . $row, 'Scenario analysis not available for this deal.');
            $sheet->getStyle('A' . $row)->getFont()->setItalic(true)->setColor(new Color($this->colors['muted']));
            return;
        }

        // Return Scenarios
        $sheet->setCellValue('A' . $row, 'RETURN SCENARIOS');
        $this->style_section_header($sheet, 'A' . $row);
        $row++;

        // Headers
        $sheet->setCellValue('A' . $row, 'Metric');
        $sheet->setCellValue('B' . $row, 'Downside');
        $sheet->setCellValue('C' . $row, 'Base Case');
        $sheet->setCellValue('D' . $row, 'Upside');
        $this->style_table_header($sheet, 'A' . $row . ':D' . $row);

        // Color headers
        $sheet->getStyle('B' . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFFEF2F2');
        $sheet->getStyle('C' . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFF0FDF4');
        $sheet->getStyle('D' . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFECFDF5');
        $row++;

        // Entry Multiple
        $sheet->setCellValue('A' . $row, 'Entry Multiple');
        $entry = $deal_financials['multiples']['ev_ebitda']['value'] ?? $deal_financials['multiples']['ev_operating_profit']['value'] ?? 'N/A';
        $entry_str = is_numeric($entry) ? number_format($entry, 1) . 'x' : $entry;
        $sheet->setCellValue('B' . $row, $entry_str);
        $sheet->setCellValue('C' . $row, $entry_str);
        $sheet->setCellValue('D' . $row, $entry_str);
        $row++;

        // Exit Multiple
        $sheet->setCellValue('A' . $row, 'Exit Multiple');
        $sheet->setCellValue('B' . $row, !empty($scenarios['downside']['exit_multiple']) ? number_format($scenarios['downside']['exit_multiple'], 1) . 'x' : 'N/A');
        $sheet->setCellValue('C' . $row, !empty($scenarios['base']['exit_multiple']) ? number_format($scenarios['base']['exit_multiple'], 1) . 'x' : 'N/A');
        $sheet->setCellValue('D' . $row, !empty($scenarios['upside']['exit_multiple']) ? number_format($scenarios['upside']['exit_multiple'], 1) . 'x' : 'N/A');
        $row++;

        // Hold Period
        $sheet->setCellValue('A' . $row, 'Hold Period (Years)');
        $sheet->setCellValue('B' . $row, $scenarios['downside']['exit_year'] ?? 6);
        $sheet->setCellValue('C' . $row, $scenarios['base']['exit_year'] ?? 5);
        $sheet->setCellValue('D' . $row, $scenarios['upside']['exit_year'] ?? 4);
        $row++;

        // IRR
        $sheet->setCellValue('A' . $row, 'IRR');
        $sheet->setCellValue('B' . $row, ($scenarios['downside']['irr'] ?? 0) . '%');
        $sheet->setCellValue('C' . $row, ($scenarios['base']['irr'] ?? 0) . '%');
        $sheet->setCellValue('D' . $row, ($scenarios['upside']['irr'] ?? 0) . '%');
        $sheet->getStyle('B' . $row)->getFont()->setColor(new Color($this->colors['negative']))->setBold(true);
        $sheet->getStyle('C' . $row)->getFont()->setColor(new Color($this->colors['text']))->setBold(true);
        $sheet->getStyle('D' . $row)->getFont()->setColor(new Color($this->colors['positive']))->setBold(true);
        $row++;

        // MOIC
        $sheet->setCellValue('A' . $row, 'MOIC');
        $sheet->setCellValue('B' . $row, ($scenarios['downside']['moic'] ?? 0) . 'x');
        $sheet->setCellValue('C' . $row, ($scenarios['base']['moic'] ?? 0) . 'x');
        $sheet->setCellValue('D' . $row, ($scenarios['upside']['moic'] ?? 0) . 'x');
        $sheet->getStyle('B' . $row)->getFont()->setColor(new Color($this->colors['negative']))->setBold(true);
        $sheet->getStyle('C' . $row)->getFont()->setColor(new Color($this->colors['text']))->setBold(true);
        $sheet->getStyle('D' . $row)->getFont()->setColor(new Color($this->colors['positive']))->setBold(true);
        $row++;

        $row++;

        // Scenario Assumptions
        $sheet->setCellValue('A' . $row, 'SCENARIO ASSUMPTIONS');
        $this->style_section_header($sheet, 'A' . $row);
        $row++;

        // Downside assumptions
        if (!empty($scenarios['downside']['assumptions'])) {
            $sheet->setCellValue('A' . $row, 'Downside Case:');
            $sheet->getStyle('A' . $row)->getFont()->setBold(true);
            $row++;
            $sheet->setCellValue('A' . $row, $scenarios['downside']['assumptions']);
            $sheet->mergeCells('A' . $row . ':D' . $row);
            $sheet->getStyle('A' . $row)->getAlignment()->setWrapText(true);
            $row++;
        }

        // Base case assumptions
        if (!empty($scenarios['base']['assumptions'])) {
            $sheet->setCellValue('A' . $row, 'Base Case:');
            $sheet->getStyle('A' . $row)->getFont()->setBold(true);
            $row++;
            $sheet->setCellValue('A' . $row, $scenarios['base']['assumptions']);
            $sheet->mergeCells('A' . $row . ':D' . $row);
            $sheet->getStyle('A' . $row)->getAlignment()->setWrapText(true);
            $row++;
        }

        // Upside assumptions
        if (!empty($scenarios['upside']['assumptions'])) {
            $sheet->setCellValue('A' . $row, 'Upside Case:');
            $sheet->getStyle('A' . $row)->getFont()->setBold(true);
            $row++;
            $sheet->setCellValue('A' . $row, $scenarios['upside']['assumptions']);
            $sheet->mergeCells('A' . $row . ':D' . $row);
            $sheet->getStyle('A' . $row)->getAlignment()->setWrapText(true);
            $row++;
        }

        // Apply borders
        $this->apply_borders($sheet, 'A3:D' . $row);
    }

    /**
     * Build Sensitivity Analysis sheet
     */
    private function build_sensitivity_sheet($spreadsheet, $post, $deal_financials) {
        $sheet = $spreadsheet->createSheet();
        $sheet->setTitle('Sensitivity Analysis');

        // Set column widths
        for ($col = 'A'; $col <= 'G'; $col++) {
            $sheet->getColumnDimension($col)->setWidth(12);
        }
        $sheet->getColumnDimension('A')->setWidth(18);

        // Header
        $sheet->setCellValue('A1', 'SENSITIVITY ANALYSIS');
        $sheet->mergeCells('A1:G1');
        $this->style_header($sheet, 'A1:G1');

        $row = 3;

        // Get base case values
        $scenarios = $deal_financials['ai_enhanced']['scenarios'] ?? $deal_financials['scenarios'] ?? array();
        $base_irr = $scenarios['base']['irr'] ?? 15;
        $entry_multiple = $deal_financials['multiples']['ev_ebitda']['value'] ?? $deal_financials['multiples']['ev_operating_profit']['value'] ?? 12;
        $base_exit = $scenarios['base']['exit_multiple'] ?? 14;

        // IRR Sensitivity Table: Exit Multiple vs Hold Period
        $sheet->setCellValue('A' . $row, 'IRR SENSITIVITY: Exit Multiple vs Hold Period');
        $this->style_section_header($sheet, 'A' . $row);
        $row++;

        // Create sensitivity matrix
        $exit_multiples = array(
            round($base_exit * 0.7, 1),
            round($base_exit * 0.85, 1),
            round($base_exit, 1),
            round($base_exit * 1.15, 1),
            round($base_exit * 1.3, 1)
        );
        $hold_periods = array(3, 4, 5, 6, 7);

        // Header row
        $sheet->setCellValue('A' . $row, 'Exit Multiple / Years');
        $col = 'B';
        foreach ($hold_periods as $years) {
            $sheet->setCellValue($col . $row, $years . ' Years');
            $col++;
        }
        $this->style_table_header($sheet, 'A' . $row . ':F' . $row);
        $row++;

        // Calculate IRR for each combination
        foreach ($exit_multiples as $exit) {
            $sheet->setCellValue('A' . $row, $exit . 'x');
            $sheet->getStyle('A' . $row)->getFont()->setBold(true);

            $col = 'B';
            foreach ($hold_periods as $years) {
                // Simple IRR approximation: IRR = (Exit/Entry)^(1/n) - 1
                $irr = (pow($exit / $entry_multiple, 1 / $years) - 1) * 100;
                $sheet->setCellValue($col . $row, number_format($irr, 1) . '%');

                // Color code
                if ($irr >= 20) {
                    $sheet->getStyle($col . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFD1FAE5');
                    $sheet->getStyle($col . $row)->getFont()->setColor(new Color('047857'));
                } elseif ($irr >= 12) {
                    $sheet->getStyle($col . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFFEF3C7');
                    $sheet->getStyle($col . $row)->getFont()->setColor(new Color('92400E'));
                } else {
                    $sheet->getStyle($col . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFFEE2E2');
                    $sheet->getStyle($col . $row)->getFont()->setColor(new Color('991B1B'));
                }

                $col++;
            }
            $row++;
        }

        $row += 2;

        // MOIC Sensitivity Table
        $sheet->setCellValue('A' . $row, 'MOIC SENSITIVITY: Exit Multiple vs Hold Period');
        $this->style_section_header($sheet, 'A' . $row);
        $row++;

        // Header row
        $sheet->setCellValue('A' . $row, 'Exit Multiple / Years');
        $col = 'B';
        foreach ($hold_periods as $years) {
            $sheet->setCellValue($col . $row, $years . ' Years');
            $col++;
        }
        $this->style_table_header($sheet, 'A' . $row . ':F' . $row);
        $row++;

        // Calculate MOIC for each combination
        foreach ($exit_multiples as $exit) {
            $sheet->setCellValue('A' . $row, $exit . 'x');
            $sheet->getStyle('A' . $row)->getFont()->setBold(true);

            $col = 'B';
            foreach ($hold_periods as $years) {
                // MOIC = Exit Multiple / Entry Multiple
                $moic = $exit / $entry_multiple;
                $sheet->setCellValue($col . $row, number_format($moic, 2) . 'x');

                // Color code
                if ($moic >= 2.5) {
                    $sheet->getStyle($col . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFD1FAE5');
                } elseif ($moic >= 1.5) {
                    $sheet->getStyle($col . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFFEF3C7');
                } else {
                    $sheet->getStyle($col . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFFEE2E2');
                }

                $col++;
            }
            $row++;
        }

        $row += 2;

        // Legend
        $sheet->setCellValue('A' . $row, 'Legend:');
        $sheet->getStyle('A' . $row)->getFont()->setBold(true);
        $row++;

        $sheet->setCellValue('A' . $row, 'Attractive (IRR >= 20% / MOIC >= 2.5x)');
        $sheet->getStyle('A' . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFD1FAE5');
        $row++;

        $sheet->setCellValue('A' . $row, 'Moderate (IRR 12-20% / MOIC 1.5-2.5x)');
        $sheet->getStyle('A' . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFFEF3C7');
        $row++;

        $sheet->setCellValue('A' . $row, 'Challenging (IRR < 12% / MOIC < 1.5x)');
        $sheet->getStyle('A' . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFFEE2E2');

        // Apply borders
        $this->apply_borders($sheet, 'A3:F' . $row);
    }

    /**
     * Build Risks sheet
     */
    private function build_risks_sheet($spreadsheet, $post, $deal_financials) {
        $sheet = $spreadsheet->createSheet();
        $sheet->setTitle('Risk Assessment');

        // Set column widths
        $sheet->getColumnDimension('A')->setWidth(15);
        $sheet->getColumnDimension('B')->setWidth(50);
        $sheet->getColumnDimension('C')->setWidth(12);
        $sheet->getColumnDimension('D')->setWidth(12);

        // Header
        $sheet->setCellValue('A1', 'RISK ASSESSMENT');
        $sheet->mergeCells('A1:D1');
        $this->style_header($sheet, 'A1:D1');

        $row = 3;

        $risks = $deal_financials['ai_enhanced']['risks'] ?? $deal_financials['risks'] ?? array();

        if (empty($risks)) {
            $sheet->setCellValue('A' . $row, 'Risk assessment not available for this deal.');
            $sheet->getStyle('A' . $row)->getFont()->setItalic(true)->setColor(new Color($this->colors['muted']));
            return;
        }

        // Risk Matrix
        $sheet->setCellValue('A' . $row, 'IDENTIFIED RISKS');
        $this->style_section_header($sheet, 'A' . $row);
        $row++;

        // Headers
        $sheet->setCellValue('A' . $row, 'Category');
        $sheet->setCellValue('B' . $row, 'Description');
        $sheet->setCellValue('C' . $row, 'Severity');
        $sheet->setCellValue('D' . $row, 'Likelihood');
        $this->style_table_header($sheet, 'A' . $row . ':D' . $row);
        $row++;

        foreach ($risks as $risk) {
            $sheet->setCellValue('A' . $row, ucfirst($risk['category'] ?? 'General'));
            $sheet->setCellValue('B' . $row, $risk['description'] ?? '');
            $sheet->getStyle('B' . $row)->getAlignment()->setWrapText(true);

            $severity = strtolower($risk['severity'] ?? 'medium');
            $sheet->setCellValue('C' . $row, ucfirst($severity));
            $severity_color = $severity === 'high' ? $this->colors['negative'] : ($severity === 'medium' ? $this->colors['warning'] : $this->colors['positive']);
            $sheet->getStyle('C' . $row)->getFont()->setColor(new Color($severity_color))->setBold(true);

            $likelihood = strtolower($risk['likelihood'] ?? 'medium');
            $sheet->setCellValue('D' . $row, ucfirst($likelihood));
            $likelihood_color = $likelihood === 'high' ? $this->colors['negative'] : ($likelihood === 'medium' ? $this->colors['warning'] : $this->colors['positive']);
            $sheet->getStyle('D' . $row)->getFont()->setColor(new Color($likelihood_color))->setBold(true);

            $row++;
        }

        $row++;

        // Risk Summary
        $sheet->setCellValue('A' . $row, 'RISK SUMMARY');
        $this->style_section_header($sheet, 'A' . $row);
        $row++;

        // Count by severity
        $high_risks = count(array_filter($risks, function($r) { return strtolower($r['severity'] ?? '') === 'high'; }));
        $medium_risks = count(array_filter($risks, function($r) { return strtolower($r['severity'] ?? '') === 'medium'; }));
        $low_risks = count(array_filter($risks, function($r) { return strtolower($r['severity'] ?? '') === 'low'; }));

        $sheet->setCellValue('A' . $row, 'High Severity');
        $sheet->setCellValue('B' . $row, $high_risks);
        $sheet->getStyle('B' . $row)->getFont()->setColor(new Color($this->colors['negative']))->setBold(true);
        $row++;

        $sheet->setCellValue('A' . $row, 'Medium Severity');
        $sheet->setCellValue('B' . $row, $medium_risks);
        $sheet->getStyle('B' . $row)->getFont()->setColor(new Color($this->colors['warning']))->setBold(true);
        $row++;

        $sheet->setCellValue('A' . $row, 'Low Severity');
        $sheet->setCellValue('B' . $row, $low_risks);
        $sheet->getStyle('B' . $row)->getFont()->setColor(new Color($this->colors['positive']))->setBold(true);

        // Apply borders
        $this->apply_borders($sheet, 'A3:D' . $row);
    }

    /**
     * Build Sources & Notes sheet
     */
    private function build_sources_sheet($spreadsheet, $post, $deal_financials) {
        $sheet = $spreadsheet->createSheet();
        $sheet->setTitle('Sources & Notes');

        // Set column widths
        $sheet->getColumnDimension('A')->setWidth(80);

        // Header
        $sheet->setCellValue('A1', 'SOURCES & METHODOLOGY');
        $this->style_header($sheet, 'A1');

        $row = 3;

        // Article Source
        $sheet->setCellValue('A' . $row, 'SOURCE ARTICLE');
        $this->style_section_header($sheet, 'A' . $row);
        $row++;

        $sheet->setCellValue('A' . $row, 'Title: ' . $post->post_title);
        $row++;

        $sheet->setCellValue('A' . $row, 'Published: ' . get_the_date('F j, Y', $post));
        $row++;

        $source_url = get_post_meta($post->ID, '_original_source_url', true);
        if (!empty($source_url)) {
            $sheet->setCellValue('A' . $row, 'Original Source: ' . $source_url);
            $row++;
        }

        $row++;

        // Data Quality Methodology
        $sheet->setCellValue('A' . $row, 'DATA QUALITY METHODOLOGY');
        $this->style_section_header($sheet, 'A' . $row);
        $row++;

        $methodology = array(
            'DISCLOSED - Data directly stated in the source article. Highest confidence.',
            'CALCULATED - Data mathematically derived from disclosed information.',
            'ESTIMATED - Data based on industry benchmarks, comparable transactions, or AI analysis.',
            'UNKNOWN - Insufficient information to determine.',
        );

        foreach ($methodology as $method) {
            $sheet->setCellValue('A' . $row, $method);
            $row++;
        }

        $row++;

        // Scenario Analysis Methodology
        $sheet->setCellValue('A' . $row, 'SCENARIO ANALYSIS METHODOLOGY');
        $this->style_section_header($sheet, 'A' . $row);
        $row++;

        $scenario_notes = array(
            'Base Case: Reflects management case or industry standard assumptions.',
            'Upside Case: Assumes favorable market conditions, operational improvements, or strategic value creation.',
            'Downside Case: Stress tests key assumptions including multiple compression and extended hold periods.',
            'IRR calculated using simplified formula: IRR = (Exit/Entry)^(1/n) - 1',
            'MOIC calculated as Exit Enterprise Value / Entry Enterprise Value',
        );

        foreach ($scenario_notes as $note) {
            $sheet->setCellValue('A' . $row, $note);
            $row++;
        }

        $row++;

        // Disclaimer
        $sheet->setCellValue('A' . $row, 'DISCLAIMER');
        $this->style_section_header($sheet, 'A' . $row);
        $row++;

        $disclaimer = "This financial model is provided for informational purposes only and does not constitute " .
                     "investment advice. All financial projections and scenario analyses are estimates based on " .
                     "publicly available information and industry benchmarks. Actual results may vary significantly " .
                     "from projections. Users should conduct their own due diligence before making investment decisions.";

        $sheet->setCellValue('A' . $row, $disclaimer);
        $sheet->getStyle('A' . $row)->getAlignment()->setWrapText(true);
        $sheet->getRowDimension($row)->setRowHeight(60);

        $row += 2;

        // Generation Info
        $sheet->setCellValue('A' . $row, 'Generated by MENA Careers');
        $sheet->getStyle('A' . $row)->getFont()->setColor(new Color($this->colors['muted']));
        $row++;

        $sheet->setCellValue('A' . $row, 'Generated: ' . date('F j, Y \a\t g:i A'));
        $sheet->getStyle('A' . $row)->getFont()->setColor(new Color($this->colors['muted']));
    }

    /**
     * Style header cell
     */
    private function style_header($sheet, $range) {
        $sheet->getStyle($range)->applyFromArray(array(
            'font' => array(
                'bold' => true,
                'size' => 16,
                'color' => array('argb' => 'FFFFFFFF'),
            ),
            'fill' => array(
                'fillType' => Fill::FILL_SOLID,
                'startColor' => array('argb' => 'FF' . $this->colors['navy']),
            ),
            'alignment' => array(
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
            ),
        ));

        // Set row height
        $row = substr($range, strpos($range, ':') !== false ? 1 : 1);
        $row = preg_replace('/[^0-9]/', '', $row);
        $sheet->getRowDimension($row)->setRowHeight(30);
    }

    /**
     * Style section header
     */
    private function style_section_header($sheet, $cell) {
        $sheet->getStyle($cell)->applyFromArray(array(
            'font' => array(
                'bold' => true,
                'size' => 12,
                'color' => array('argb' => 'FF' . $this->colors['navy']),
            ),
            'fill' => array(
                'fillType' => Fill::FILL_SOLID,
                'startColor' => array('argb' => 'FF' . $this->colors['light_blue']),
            ),
        ));
    }

    /**
     * Style table header
     */
    private function style_table_header($sheet, $range) {
        $sheet->getStyle($range)->applyFromArray(array(
            'font' => array(
                'bold' => true,
                'color' => array('argb' => 'FFFFFFFF'),
            ),
            'fill' => array(
                'fillType' => Fill::FILL_SOLID,
                'startColor' => array('argb' => 'FF' . $this->colors['green']),
            ),
            'alignment' => array(
                'horizontal' => Alignment::HORIZONTAL_CENTER,
            ),
        ));
    }

    /**
     * Apply borders to range
     */
    private function apply_borders($sheet, $range) {
        $sheet->getStyle($range)->applyFromArray(array(
            'borders' => array(
                'allBorders' => array(
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => array('argb' => 'FF' . $this->colors['border']),
                ),
            ),
        ));
    }

    /**
     * Format currency value
     */
    private function format_currency($amount, $currency = 'USD') {
        $symbols = array(
            'USD' => '$',
            'GBP' => '£',
            'EUR' => '€',
            'JPY' => '¥',
        );

        $symbol = $symbols[$currency] ?? $currency . ' ';

        if ($amount >= 1000000000) {
            return $symbol . number_format($amount / 1000000000, 2) . 'bn';
        } elseif ($amount >= 1000000) {
            return $symbol . number_format($amount / 1000000, 1) . 'm';
        } elseif ($amount >= 1000) {
            return $symbol . number_format($amount / 1000, 1) . 'k';
        }

        return $symbol . number_format($amount, 0);
    }

    /**
     * Get human-readable source label
     */
    private function get_source_label($source) {
        $labels = array(
            'disclosed' => 'Disclosed',
            'calculated' => 'Calculated',
            'estimated' => 'Estimated',
            'unknown' => 'Unknown',
        );

        return $labels[strtolower($source)] ?? ucfirst($source);
    }

    /**
     * Generate unique filename
     */
    private function generate_filename($post) {
        $title = sanitize_file_name($post->post_title);
        $title = substr($title, 0, 50); // Limit length
        $timestamp = date('Ymd_His');
        $random = substr(md5(uniqid()), 0, 6);

        return sprintf('Deal_Model_%s_%s_%s.xlsx', $title, $timestamp, $random);
    }

    /**
     * Create secure download URL
     */
    private function create_download_url($filename, $post_id) {
        $nonce = wp_create_nonce('download_deal_model_' . $filename);

        return add_query_arg(array(
            'action' => 'sffc_download_deal_model',
            'file' => $filename,
            'post_id' => $post_id,
            'nonce' => $nonce,
        ), admin_url('admin-ajax.php'));
    }

    /**
     * Track download for analytics
     */
    private function track_download($post_id) {
        $downloads = get_post_meta($post_id, '_sffc_model_downloads', true);
        $downloads = is_numeric($downloads) ? (int) $downloads : 0;
        update_post_meta($post_id, '_sffc_model_downloads', $downloads + 1);
        update_post_meta($post_id, '_sffc_last_model_download', current_time('mysql'));
    }

    /**
     * Handle file download (static method for AJAX)
     */
    public static function handle_download() {
        // Verify nonce
        if (!isset($_GET['nonce']) || !isset($_GET['file'])) {
            wp_die('Invalid request');
        }

        $filename = sanitize_file_name($_GET['file']);

        if (!wp_verify_nonce($_GET['nonce'], 'download_deal_model_' . $filename)) {
            wp_die('Security check failed');
        }

        // Build file path
        $filepath = plugin_dir_path(dirname(__FILE__)) . 'exports/generated/' . $filename;

        if (!file_exists($filepath)) {
            wp_die('File not found');
        }

        // Send download headers
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment; filename="' . basename($filename) . '"');
        header('Content-Length: ' . filesize($filepath));
        header('Cache-Control: private, no-cache, no-store, must-revalidate');
        header('Pragma: no-cache');
        header('Expires: 0');

        // Output file
        readfile($filepath);
        exit;
    }

    /**
     * Clean up old generated files
     */
    public function cleanup_old_files($max_age_hours = 24) {
        $files = glob($this->generated_dir . 'Deal_Model_*.xlsx');
        $cutoff = time() - ($max_age_hours * 3600);

        foreach ($files as $file) {
            if (filemtime($file) < $cutoff) {
                unlink($file);
            }
        }
    }
}

} // End if (!class_exists('SFFC_Deal_Excel_Generator'))

// Register AJAX handlers
add_action('wp_ajax_sffc_download_deal_model', array('SFFC_Deal_Excel_Generator', 'handle_download'));
add_action('wp_ajax_nopriv_sffc_download_deal_model', array('SFFC_Deal_Excel_Generator', 'handle_download'));

// Register AJAX handler for generating model
add_action('wp_ajax_sffc_generate_deal_model', function() {
    // Verify nonce
    if (!isset($_POST['nonce']) || !wp_verify_nonce($_POST['nonce'], 'sffc_deal_model_nonce')) {
        wp_send_json_error(array('message' => 'Security check failed'));
    }

    // Get post ID
    $post_id = isset($_POST['post_id']) ? intval($_POST['post_id']) : 0;
    if (!$post_id) {
        wp_send_json_error(array('message' => 'Invalid post ID'));
    }

    // Generate Excel
    $generator = new SFFC_Deal_Excel_Generator();
    $result = $generator->generate($post_id);

    if ($result['success']) {
        wp_send_json_success($result);
    } else {
        wp_send_json_error($result);
    }
});
